### ISSUE TITLE
generate oncoscan.tsv file

### ISSUE THREAD

**Issue by apastore** [fredcommo/rCGH#6]
Hi Thanks for this project, I think is realy useful! I get from a collaborator oncoscan CNV FFPE array. I have seen in your tutorial that you provide a oncoscan.TSV file. Could you explain (even if is not part of this package) how to generate a valid oncoscan (TSV) input file?

Thanks a lot!

**Comment by fredcommo** [comment]
Hi,

Sorry for my late reply, and thanks for your positive comments.
You have to use the Affymetrix Software, or the Affymetrix Power Tools, with which you can write your own command line code.

http://media.affymetrix.com/support/developer/powertools/changelog/VIGNETTE-OncoScan-ssa.html

I’ve built a package which does the job, but since it includes Affymetrix libraries, it’s too big to be published in bioconductor (>200Mo).

Hope this help,
Fred

**Comment by apastore** [comment]
Thanks! 

apt2-dset-util export hdf5 to tsv. 

http://media.affymetrix.com/support/developer/powertools/changelog/apt2-dset-util.html
